os:
  - Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Release

before_build:
  - git submodule init
  - git submodule update --depth=1
  - cmake -H. -Bbuild -A%PLATFORM%

build:
  project: build\OpenCL-SDK.sln
  parallel: true
  verbosity: normal
