
language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

jobs:
  include:
  - if: branch = master
    os: linux
    dist: bionic
    env: JOB_CHECK_FORMAT=1
    addons:
        apt:
          packages:
            - clang-format-9

script:
  - ./scripts/travis.sh
