stages:
  - build   # Test if headers build and install (CMake)
  - test    # Test if unit tests pass (CTest)
  - consume # Test if downstream can depend on installs (CMake)

variables:
  # GIT_SUBMODULE_STRATEGY missing on purpose. When submodules
  # are specified using SSH protocol, they are mapped to HTTPS
  # in the before_script part.
  DEPS_DIR:      "$CI_PROJECT_DIR/dependencies"
  BUILD_DIR:     "$CI_PROJECT_DIR/build"
  INSTALL_DIR:   "$CI_PROJECT_DIR/install"
  CMAKE_MINIMUM: "3.10.3"
  CMAKE_LATEST:  "3.21.2"

########################
##                    ##
## Setup environments ##
##                    ##
########################

.toolchain-matrix-minimum:
  image: streamhpc/opencl-sdk-base:ubuntu-18.04-20211117
  parallel:
    matrix:
  # NOTE: Old CMake versions will likely not use cutting-edge compilers
      - C_COMPILER: gcc-7
        CXX_COMPILER: g++-7
      - C_COMPILER: gcc-8
        CXX_COMPILER: g++-8
      - C_COMPILER: clang-8
        CXX_COMPILER: clang++-8
      - C_COMPILER: clang-9
        CXX_COMPILER: clang++-9
      - C_COMPILER: clang-10
        CXX_COMPILER: clang++-10
  before_script:
    - export PATH=/opt/Kitware/CMake/$CMAKE_MINIMUM/bin:$PATH
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@projects.streamhpc.com/".insteadOf "git@projects.streamhpc.com:"
    - git submodule sync && git submodule update --init --recursive

.toolchain-matrix-latest:
  image: streamhpc/opencl-sdk-base:ubuntu-18.04-20211117
  parallel:
    matrix:
  # NOTE: Cutting edge CMake versions will likely not use old compilers
      - C_COMPILER: gcc-9
        CXX_COMPILER: g++-9
      - C_COMPILER: gcc-10
        CXX_COMPILER: g++-10
      - C_COMPILER: clang-11
        CXX_COMPILER: clang++-11
      - C_COMPILER: clang-12
        CXX_COMPILER: clang++-12
      - C_COMPILER: clang-13
        CXX_COMPILER: clang++-13
  before_script:
    - export PATH=/opt/Kitware/CMake/$CMAKE_LATEST/bin:$PATH
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@projects.streamhpc.com/".insteadOf "git@projects.streamhpc.com:"
    - git submodule sync && git submodule update --init --recursive

.exec-matrix-minimum:
  parallel:
    matrix:
  # NOTE: Old CMake versions will likely not use cutting-edge compilers
      - C_COMPILER: gcc-7
        CXX_COMPILER: g++-7
      - C_COMPILER: gcc-8
        CXX_COMPILER: g++-8
      - C_COMPILER: clang-8
        CXX_COMPILER: clang++-8
      - C_COMPILER: clang-9
        CXX_COMPILER: clang++-9
      - C_COMPILER: clang-10
        CXX_COMPILER: clang++-10
  before_script:
    - export PATH=/opt/Kitware/CMake/$CMAKE_MINIMUM/bin:$PATH

.exec-matrix-latest:
  parallel:
    matrix:
  # NOTE: Cutting edge CMake versions will likely not use old compilers
      - C_COMPILER: gcc-9
        CXX_COMPILER: g++-9
      - C_COMPILER: gcc-10
        CXX_COMPILER: g++-10
      - C_COMPILER: clang-11
        CXX_COMPILER: clang++-11
      - C_COMPILER: clang-12
        CXX_COMPILER: clang++-12
      - C_COMPILER: clang-13
        CXX_COMPILER: clang++-13
  before_script:
    - export PATH=/opt/Kitware/CMake/$CMAKE_LATEST/bin:$PATH

#################
##             ##
## Build stage ##
##             ##
#################

build:cmake-minimum:
  extends: .toolchain-matrix-minimum
  stage: build
  # NOTE 1: CMake creates build and install folders as needed.
  # NOTE 2: Lack of space in -H<folder> -B<folder> is important!
  #         https://stackoverflow.com/a/20611964/1476661
  script:
    # Clone, configure, build, install OpenCL-SDK
    - cmake
      -G Ninja
      -D CMAKE_TOOLCHAIN_FILE=/opt/Microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake
      -D CMAKE_C_COMPILER=$C_COMPILER
      -D CMAKE_CXX_COMPILER=$CXX_COMPILER
      -D CMAKE_BUILD_TYPE=Release
      -D BUILD_TESTING=ON
      -D ENABLE_OPENCL_LAYERS=ON
      -D OPENCL_ICD_LOADER_BUILD_TESTING=ON
      -D BUILD_DOCS=OFF
      -D BUILD_EXAMPLES=OFF
      -D BUILD_TESTS=ON
      -D OPENCL_SDK_BUILD_SAMPLES=ON
      -D OPENCL_SDK_TEST_SAMPLES=ON
      -D CMAKE_INSTALL_PREFIX=$INSTALL_DIR
      -B$BUILD_DIR
      -H$CI_PROJECT_DIR
    - cmake
      --build $BUILD_DIR
      --target install
  artifacts:
    paths:
      - $BUILD_DIR
      - $INSTALL_DIR
    exclude:
      - build/**/CMakeFiles/
    expire_in: 2 weeks

build:cmake-latest:
  extends: .toolchain-matrix-latest
  stage: build
  script:
    # Clone, configure, build, install OpenCL-SDK
    - cmake
      -G "Ninja Multi-Config"
      -D CMAKE_TOOLCHAIN_FILE=/opt/Microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake
      -D CMAKE_C_COMPILER=$C_COMPILER
      -D CMAKE_CXX_COMPILER=$CXX_COMPILER
      -D BUILD_TESTING=ON
      -D ENABLE_OPENCL_LAYERS=ON
      -D OPENCL_ICD_LOADER_BUILD_TESTING=ON
      -D BUILD_DOCS=OFF
      -D BUILD_EXAMPLES=OFF
      -D BUILD_TESTS=ON
      -D OPENCL_SDK_BUILD_SAMPLES=ON
      -D OPENCL_SDK_TEST_SAMPLES=ONINSTALL_DIR
      -B $BUILD_DIR
      -S $CI_PROJECT_DIR
    - cmake
      --build $BUILD_DIR
      --config Debug
      --target install
    - cmake
      --build $BUILD_DIR
      --config Release
      --target install
  artifacts:
    paths:
      - $BUILD_DIR
      - $INSTALL_DIR
    exclude:
      - build/**/CMakeFiles/
    expire_in: 2 weeks


################
##            ##
## Test stage ##
##            ##
################

test:cmake-minimum-rocm:
  extends: .exec-matrix-minimum
  image: streamhpc/opencl-sdk-rocm:ubuntu-18.04-20211117
  tags:
    - rocm-stable
  stage: test
  needs:
    - build:cmake-minimum
  # NOTE: CTest has to be invoked from the build folder.
  script:
    - cd $BUILD_DIR
    - ctest --output-on-failure

test:cmake-latest-rocm:
  extends: .exec-matrix-latest
  image: streamhpc/opencl-sdk-rocm:ubuntu-18.04-20211117
  tags:
    - rocm-stable
  stage: test
  needs:
    - build:cmake-latest
  # NOTE: CTest has to be invoked from the build folder.
  script:
    - cd $BUILD_DIR
    - ctest --output-on-failure -C Debug
    - ctest --output-on-failure -C Release 

###################
##               ##
## Consume stage ##
##               ##
###################

consume:cmake-minimum:
  extends: .toolchain-matrix-minimum
  stage: consume
  needs:
    - build:cmake-minimum
  # NOTE 1: CMake creates build and install folders as needed.
  # NOTE 2: Lack of space in -H<folder> -B<folder> is important!
  #         https://stackoverflow.com/a/20611964/1476661
  script:
    # Test Package Config dependence
    - cmake
      -G Ninja
      -D CMAKE_C_COMPILER=$C_COMPILER
      -D CMAKE_CXX_COMPILER=$CXX_COMPILER
      -D CMAKE_BUILD_TYPE=Release
      -D CMAKE_PREFIX_PATH=$INSTALL_DIR
      -D BUILD_TESTING=ON
      -B$CI_PROJECT_DIR/downstream/pkgconfig
      -H$CI_PROJECT_DIR/test/cmake/pkgconfig
    - cmake
      --build $CI_PROJECT_DIR/downstream/pkgconfig
    - cd $CI_PROJECT_DIR/downstream/pkgconfig
    - ctest --output-on-failure
    # Test Find Module dependence
    - cmake
      -G Ninja
      -D CMAKE_C_COMPILER=$C_COMPILER
      -D CMAKE_CXX_COMPILER=$CXX_COMPILER
      -D CMAKE_BUILD_TYPE=Release
      -D CMAKE_PREFIX_PATH=$INSTALL_DIR
      -D BUILD_TESTING=ON
      -B$CI_PROJECT_DIR/downstream/findmodule
      -H$CI_PROJECT_DIR/test/cmake/findmodule
    - cmake
      --build $CI_PROJECT_DIR/downstream/findmodule
    - cd $CI_PROJECT_DIR/downstream/findmodule
    - ctest --output-on-failure

consume:cmake-latest:
  extends: .toolchain-matrix-latest
  stage: consume
  needs:
    - build:cmake-latest
  script:
    # Test Package Config dependence
    - cmake
      -G "Ninja Multi-Config"
      -D CMAKE_C_COMPILER=$C_COMPILER
      -D CMAKE_CXX_COMPILER=$CXX_COMPILER
      -D CMAKE_PREFIX_PATH=$INSTALL_DIR
      -D BUILD_TESTING=ON
      -B $CI_PROJECT_DIR/downstream/pkgconfig
      -S $CI_PROJECT_DIR/test/cmake/pkgconfig
    - cmake
      --build $CI_PROJECT_DIR/downstream/pkgconfig
      --config Debug
    - cmake
      --build $CI_PROJECT_DIR/downstream/pkgconfig
      --config Release
    - cd $CI_PROJECT_DIR/downstream/pkgconfig
    - ctest --output-on-failure -C Debug
    - ctest --output-on-failure -C Release
    # Test Find Module dependence
    - cmake
      -G "Ninja Multi-Config"
      -D CMAKE_C_COMPILER=$C_COMPILER
      -D CMAKE_CXX_COMPILER=$CXX_COMPILER
      -D CMAKE_PREFIX_PATH=$INSTALL_DIR
      -D BUILD_TESTING=ON
      -B $CI_PROJECT_DIR/downstream/findmodule
      -S $CI_PROJECT_DIR/test/cmake/findmodule
    - cmake
      --build $CI_PROJECT_DIR/downstream/findmodule
      --config Debug
    - cmake
      --build $CI_PROJECT_DIR/downstream/findmodule
      --config Release
    - cd $CI_PROJECT_DIR/downstream/findmodule
    - ctest --output-on-failure -C Debug
    - ctest --output-on-failure -C Release
